distro: add missing build deps
autoreconf: command not found

Can't exec "aclocal": No such file or directory at ...
autoreconf: failed to run aclocal: No such file or directory

error: Libtool library used but 'LIBTOOL' is undefined