python/setup: remove absolute path to package
This reverts 10516d0905f8d27031f851ebb10e88d672dfd173, which broke installation
from PyPi with the message:
error: package directory '...' does not exist